Match User gpu-tunnel
    PasswordAuthentication no
    PubkeyAuthentication yes
    PermitTTY no
    AllowTcpForwarding yes
    GatewayPorts clientspecified
    X11Forwarding no
    AllowAgentForwarding no
