bindPort = 7000

transport.tls.force = true

allowPorts = [
  { single = 6022 }
]

auth.method = "token"
auth.additionalScopes = ["HeartBeats", "NewWorkConns"]
auth.tokenSource.type = "file"
auth.tokenSource.file.path = "/etc/frp/server_token"
